// RUN: dlopt %s --print-ir | FileCheck %s

module "mnist"
stage raw

struct $MNIST {
    #w: f32
    #b: f32
}

type $MyMnist = $MNIST

func @inference: (f32, f32, f32) -> f32 {
'entry(%x: f32, %w: f32, %b: f32):
    %0.0 = multiply %x: f32, %w: f32
    %0.1 = add %0.0: f32, %b: f32
    return %0.1: f32
}

// CHECK-LABEL: func @inference
// CHECK: %0.0 = multiply %x: f32, %w: f32
// CHECK-NEXT: %0.1 = add %0.0: f32, %b: f32
// CHECK-NEXT: return %0.1: f32
